language: python
python:
    - "2.7"
install:
    - "pip install ."
    - "pip install coveralls"
script:
    - "coverage run --source=hinditokenizer -m test.test_tokenizer"
after_script:
    - coveralls
